# Generated by Django 5.1.5 on 2025-01-27 09:05

import CarDekho_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarDekho_app", "0002_carlist_chassisnumber_carlist_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showroomlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="carlist",
            name="chassisNumber",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[CarDekho_app.models.alphanumeric],
            ),
        ),
    ]
