# Generated by Django 5.1.5 on 2025-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="genre",
            field=models.CharField(default="feelGood", max_length=200),
        ),
    ]
